"""create clinical cases and media

Revision ID: 684341ff0b23
Revises: f27cd5a3b675
Create Date: 2026-01-25 11:58:20.912328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684341ff0b23'
down_revision: Union[str, Sequence[str], None] = 'f27cd5a3b675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dentist_user_id', sa.Integer(), nullable=False),
    sa.Column('dentist_state', sa.String(length=2), nullable=True),
    sa.Column('dentist_municipality', sa.String(length=120), nullable=True),
    sa.Column('unit_name', sa.String(length=200), nullable=True),
    sa.Column('case_date', sa.DateTime(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('sus_card', sa.String(length=32), nullable=False),
    sa.Column('patient_phone', sa.String(length=32), nullable=True),
    sa.Column('patient_sex', sa.String(length=20), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_city', sa.String(length=120), nullable=True),
    sa.Column('patient_state', sa.String(length=2), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('hpi', sa.Text(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('dental_history', sa.Text(), nullable=True),
    sa.Column('habits', sa.Text(), nullable=True),
    sa.Column('meds_history', sa.Text(), nullable=True),
    sa.Column('vitals', sa.Text(), nullable=True),
    sa.Column('oral_description', sa.Text(), nullable=True),
    sa.Column('dentist_hypotheses', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'assigned', 'answered', 'closed', name='casestatus'), nullable=False),
    sa.Column('is_biopsied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dentist_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_cases_dentist_user_id'), 'clinical_cases', ['dentist_user_id'], unique=False)
    op.create_index(op.f('ix_clinical_cases_id'), 'clinical_cases', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_cases_status'), 'clinical_cases', ['status'], unique=False)
    op.create_table('case_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'exam', 'video', 'consent', name='mediatype'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_media_case_id'), 'case_media', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_media_id'), 'case_media', ['id'], unique=False)
    op.create_index(op.f('ix_case_media_media_type'), 'case_media', ['media_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_media_media_type'), table_name='case_media')
    op.drop_index(op.f('ix_case_media_id'), table_name='case_media')
    op.drop_index(op.f('ix_case_media_case_id'), table_name='case_media')
    op.drop_table('case_media')
    op.drop_index(op.f('ix_clinical_cases_status'), table_name='clinical_cases')
    op.drop_index(op.f('ix_clinical_cases_id'), table_name='clinical_cases')
    op.drop_index(op.f('ix_clinical_cases_dentist_user_id'), table_name='clinical_cases')
    op.drop_table('clinical_cases')
    # ### end Alembic commands ###
