"""create professional profiles

Revision ID: f27cd5a3b675
Revises: 240382e65bef
Create Date: 2026-01-25 11:07:32.833518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27cd5a3b675'
down_revision: Union[str, Sequence[str], None] = '240382e65bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('municipality', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('cro', sa.String(length=50), nullable=False),
    sa.Column('unit_name', sa.String(length=200), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('has_specialization', sa.Boolean(), nullable=False),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('teleconsultant_state', sa.String(length=2), nullable=True),
    sa.Column('teleconsultant_certificate_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_professional_profiles_id'), 'professional_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_profiles_id'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    # ### end Alembic commands ###
